type Query {
  info: String!
  product: [Good!]!
  users: [users!]!
}

type users {
  id: ID!
  name: String!
  email: String!
  password: String!
}

type Good {
  id: ID!
  description: String!
  price: Int!
  count: Int
}

type Mutation {
  add(description: String!, price: Int!, count: Int!): Good!
}
